### ISSUE TITLE
Conditional field visibility broken with checkboxes

### ISSUE THREAD

**Issue by jolora** [lucky-media/formatic#2]
I'm struggling to get a text field to show conditionally when another checkbox field has an option selected.

To reproduce the error please just take a look at[ your own demo](https://formatic.luckymedia.dev/employment-application-compact) and select "Other (please specify)" from the referral options. You'll see that your hidden "referrer_other" field remains hidden despite having `x-if='Statamic.$conditions.showField({"if":{"referral":"contains other"}}, $data.dynamic_form)'` assigned to its surrounding `<template>`

**Comment by lokmanm** [comment]
@jolora yeah this does sound like a bug. We will investigate this and release a fix ASAP.

Thanks for reporting it!

**Comment by lokmanm** [comment]
@jolora no worries, we will have someone take a look ASAP and I will let you know as soon as we release it!

**Comment by lokmanm** [comment]
Hey @jolora here is the [commit](https://github.com/lucky-media/formatic/commit/4606e433f9eaf892d86d3460705e0aade7636182) that fixes this issue!

Let me know if you stumble upon anything else.

**Comment by jolora** [comment]
Lovely, works a treat! Thanks @lokmanm and @Afan417
