### ISSUE TITLE
Toggle values always return as "true"

### ISSUE THREAD

**Issue by mikemartin** [lucky-media/formatic#9]
Hey @lokmanm 
It took me a while to debug this, but it looks like Toggle fields are always stored as "true" after form submission.

It appears that it is related to the content type. Formatic.js sets the content-type header to multpart/form-data and it seems like it is returning the toggle values to true because it interprets the toggle values as strings. 

```
const response = await this.form.submit({
                headers: { "Content-Type": "multipart/form-data" },
            });
```

I've been able to resolve the issue by removing the content type altogether, but I don't know if this is the correct fix and if it would impact form uploads.

```
const response = await this.form.submit();
```

<img width="581" alt="Screenshot_2024-07-22_at_3 08 17_PM" src="https://github.com/user-attachments/assets/c36b6f4d-20ba-4bb4-8f8d-2a406d36c35a">

**Comment by lokmanm** [comment]
Hey @mikemartin,

Thanks for filing this. We will take a look and submit a fix ASAP.

If we remove the header the file uploads wont work, so we have to check if something else is messing up the values.

**Comment by lokmanm** [comment]
@mikemartin

We just updated the code; you can check out the changes.

When an asset was being uploaded, the Statamic Form Controller would merge the current form data with the asset, turning everything into a string.

Instead of waiting for a fix from Statamic, we added some quick cleanup code for all the false values, and that fixed the issue.

Thanks for bringing this up!

**Comment by mikemartin** [comment]
@lokmanm Thanks! Just to clarify I wasn't using an asset field in my form when I experienced the issue. Does the fix still apply?

**Comment by lokmanm** [comment]
@mikemartin yes, based on your bug we also found the asset one. I guess you could say we killed two birds with one stone 😀
